// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy.proto

package com.proto.policy;

public interface PolicyIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:introspect.swapnil.insurance.PolicyId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
