// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy.proto

package com.proto.policy;

public interface PolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:introspect.swapnil.insurance.Policy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string custName = 4;</code>
   * @return The custName.
   */
  java.lang.String getCustName();
  /**
   * <code>string custName = 4;</code>
   * @return The bytes for custName.
   */
  com.google.protobuf.ByteString
      getCustNameBytes();

  /**
   * <code>int32 custId = 5;</code>
   * @return The custId.
   */
  int getCustId();
}
